### PR TITLE
Check Fix

### PR DESCRIPTION
**Pull request by AsmedDev**
Fixed the CheckManager and fixed Crash Bug on 1.8.x

### CODE REVIEW

**Comment by ilovefuud** [comment]
Is this a client crash? I don't think an ender portal teleport crashes either the client or server. @AsmedDev

**Comment by AsmedDev** [comment]
Its a Server Crash

**Comment by AsmedDev** [comment]
Just place a bed under a End Portal, wait until it's night, sleep and then the Server will Crash.

**Comment by ilovefuud** [comment]
We'll need to do this a better way then, by possibly not allowing them to lay in the bed if there's ender portal blocks nearby.

**Comment by ilovefuud** [comment]
[01:52:48 ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:841) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_192]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_192]
        at net.minecraft.server.v1_8_R3.WorldServer.e(WorldServer.java:316) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:220) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        ... 4 more
[01:52:48 ERROR]:       Cause of unexpected exception was
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_192]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_192]
        at net.minecraft.server.v1_8_R3.WorldServer.e(WorldServer.java:316) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:220) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:830) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) ~[patched.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

**Comment by AsmedDev** [comment]
But why? I mean that this does not affect players who are not trying to crash the server, and the method that does not allow it would affect players who are not trying to crash the server.

**Comment by ilovefuud** [comment]
AFAIK it doesn't crash the server, only the client. I will fix this myself and not allow them to sleep below an end portal

**Pull request closed without merging**
